name: visit_card
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_multi_carousel: ^1.0.3
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

RenderBox was not laid out: RenderViewport#3daf7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE

flutter:

  uses-material-design: true

  
  assets:
    - assets/

